### ISSUE TITLE
EXEs not being created due to build problems

### ISSUE THREAD

**Issue by rodneylive** [HackOvert/AntiDBG#2]
Any idea why I would get the following build warning and subsequent error message?

> Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB8065	Custom build for item "AntiDBG.asm" succeeded, but specified output "c:\antidbg-master\x64\debug\antidbg.obj" has not been created. This may cause incremental build to work incorrectly.	AntiDBG	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	240

> Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'C:\AntiDBG-master\x64\Debug\\AntiDBG.obj'	AntiDBG	C:\AntiDBG-master\antidbg\LINK	1

**Comment by rodneylive** [comment]
BTW, using Microsoft Visual Studio Professional 2019 Version 16.9.4

**Comment by rodneylive** [comment]
You have to build for "x86".  Closing issue.

**Comment by cetfor** [comment]
That's interesting.  You should be able to build for 64-bit without any issues.  The main difference between the x86 and x64 builds is that x64 in-line assembly isn't allowed in Visual Studio.  So there are additional files that need to be accessed.
